kind: Secret
apiVersion: v1
metadata:
  namespace: default
  name: example-secret
  annotations:
    avp_path: "secret/data/argocd"
type: Opaque
stringData:
  username: <path:secret/data/argocd#username>
  password: <path:secret/data/argocd#password>
